---
- name: Setup up htpasswd oauth
  hosts: bastion
  connection: local
  tasks:
  
  - name: Create password file and add users
    community.general.htpasswd:
      path: working/htpasswd
      name: "{{ item }}"
      password: "1qaz@WSX"
      mode: 0640
    loop:
      - admin
      - monitor
      - developer
  
  - name: Check for the existing htpasswd secret
    command: "oc get secret htpasswd-secret -n openshift-config"
    ignore_errors: yes
    register: test_result
    
  - name: Create the htpasswd secret
    command: "oc create secret generic htpasswd-secret --from-file=htpasswd=working/htpasswd -n openshift-config"
    when: "'(NotFound)' in test_result.stderr or 'No resources found' in test_result.stderr"
        
  - name: Apply the HTPasswd OAuth CR
    k8s:
      state: present
      src: files/htpasswd-cr.yaml
      
  - name: Add cluster-admin role to admin
    command: "oc adm policy add-cluster-role-to-user cluster-admin admin"
    
  - name: Add openshift_cluster_monitoring_operator role to monitor
    command: "oc adm policy add-cluster-role-to-user openshift_cluster_monitoring_operator monitor"
    
    
